version: '3'

services:
  web: 
    container_name: ${APP_NAME}_web
    build:
      context: ./api
    ports:
      - 9000:80
    volumes:
      - ./api:/var/www/app
    depends_on:
      - db

  db:
    container_name: ${APP_NAME}_mysql
    image: mysql
    ports:
      - "8989:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  client:
    container_name: ${APP_NAME}_app
    build: client
    volumes:
      - './client:/app'
    ports:
      - '5000:80'
    depends_on: 
      - web